var E=function(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");};
var I=function(){return"m"+Math.random().toString(36).slice(2,14);};
var T=function(){return new Date().toISOString().slice(0,10);};
function Q(m,type){var t=document.querySelector(".toast");if(!t)return;var icon="",bg="var(--gold)",bar="rgba(255,255,255,.6)";if(type==="err"){icon="✕ ";bg="rgba(154,59,42,.96)";}else if(type==="warn"){icon="! ";bg="rgba(166,124,61,.96)";}else if(type==="info"){icon="ℹ ";bg="rgba(166,58,43,.96)";}else{icon="✓ ";}t.innerHTML=icon+m;t.className="toast show";t.style.background=bg;t.style.borderLeft="4px solid "+bar;setTimeout(function(){t.classList.remove("show");},2600);}
var _zT=null,_zL=0;
function Z(){var now=Date.now();if(now-_zL>400){_zL=now;try{localStorage.setItem("tzs_db",JSON.stringify(D));}catch(e){}return;}clearTimeout(_zT);_zT=setTimeout(function(){_zL=Date.now();try{localStorage.setItem("tzs_db",JSON.stringify(D));}catch(e){}},400);}
try{window.addEventListener("beforeunload",function(){try{localStorage.setItem("tzs_db",JSON.stringify(D));}catch(e){}});}catch(e){}
function CONFIRM(fn){
var m=document.createElement("div");m.className="_cmodal";m.style="position:fixed;inset:0;background:rgba(0,0,0,.35);z-index:999;display:flex;align-items:center;justify-content:center";m.onclick=function(e){if(e.target===this)this.remove();};
m._cfmFn=fn;
m.innerHTML='<div style="background:var(--card);border-radius:14px;padding:24px;width:360px;box-shadow:0 8px 40px rgba(0,0,0,.12)" onclick="event.stopPropagation()"><div style="font-size:16px;font-weight:500;margin-bottom:18px">确定要删除吗？此操作不可恢复</div><div style="display:flex;gap:10px;justify-content:flex-end"><button class="btn" onclick="this.closest(\'.\_cmodal\').remove()">取消</button><button class="btn btn-primary" onclick="CFM(this)">确定</button></div></div>';
document.body.appendChild(m);}
function CFM(btn){var m=btn?btn.closest("._cmodal"):null;if(!m)return;var fn=m._cfmFn;m.remove();if(typeof fn==="function")fn();}
function V(){try{var r=localStorage.getItem("tzs_db");if(r){var p=JSON.parse(r);if(p&&(!p.meetings||!p.meetings.length)){p.meetings=D.meetings.slice();}if(p&&(!p.classActs||!p.classActs.length)){p.classActs=D.classActs.slice();}if(p&&(!p.activities||!p.activities.length)){p.activities=D.activities.slice();}Object.assign(D,p);}}catch(e){}}
function N(p){P=p;document.querySelectorAll(".nav-item").forEach(function(n){n.classList.toggle("active",n.dataset.page===p);});var t={"dash":"工作台总览","health":"数据健康度","graph":"知识图谱","members":"团员台账","meetings":"三会两制一课","students":"全班花名册","classfund":"班费考勤","attendance":"考勤记录","classact":"活动记录","activities":"通知公告","volunteer":"劳动实践","awards":"荣誉实践","honors":"荣誉墙","groups":"群情报","todos":"待办","personal":"个人事务","smart":"智慧团建","ai":"norm","photos":"班级相册","knowledge":"知识中心","aiwork":"个人AI工作台","wiki":"Wiki层","materials":"素材层","books":"书架","daily":"每日热点","social":"社媒洞察","ideas":"灵感库","content":"内容中心"};var el=document.querySelector("#pageTitle");if(el)el.textContent=t[p]||"";var wbEmbeds={aiwork:1,wiki:1,materials:1,books:1,daily:1,social:1,ideas:1,content:1};var ph=document.querySelector(".topbar h2");if(ph)ph.style.display=wbEmbeds[p]?"none":"";if(W[p])document.querySelector("#content").innerHTML=W[p]();if(window.G_SIM){G_SIM.stop();G_SIM=null;}if(p==="graph"){setTimeout(function(){GZOOM();GRAPH_SIM();},60);}var amb=document.getElementById("tzsAmbient");if(amb)amb.style.display=(p==="dash"||p==="aiwork")?"block":"none";U();}
function R(){var old=document.querySelector('[data-rnd]');if(old)old.remove();var m=D.members[Math.floor(Math.random()*D.members.length)];var h='<div data-rnd style="position:fixed;inset:0;background:rgba(0,0,0,.4);z-index:999;display:flex;align-items:center;justify-content:center" onclick="if(event.target===this)this.remove()"><div style="background:var(--card);border-radius:20px;padding:32px 44px;text-align:center;box-shadow:0 8px 40px rgba(0,0,0,.15)" onclick="event.stopPropagation()"><div style="margin-bottom:8px">'+INK.seal+'</div><div style="font-size:22px;font-weight:500;color:var(--primary);margin:8px 0">'+E(m.name)+'</div><div style="font-size:13px;color:var(--text2)">'+E(m.dorm||'')+' '+m.memberType+'</div><div style="margin-top:18px"><button class="btn btn-sm" onclick="this.closest(\'[style*=fixed]\').remove()">关闭</button> <button class="btn btn-sm btn-primary" onclick="this.closest(\'[style*=fixed]\').remove();R()">再来</button></div></div></div>';document.body.insertAdjacentHTML("beforeend",h);}
function C(){var t=document.documentElement.getAttribute("data-theme"),i="ai";if(!t||t==="ai"){i="paper";Q("已切换 · 宣纸");}else if(t==="paper"){i="bamboo";Q("已切换 · 竹青");}else if(t==="bamboo"){i="plum";Q("已切换 · 梅红");}else if(t==="plum"){i="night";Q("已切换 · 墨夜暗色");}else if(t==="night"){i="pink";Q("已切换 · 粉璃");}else if(t==="pink"){i="codex";Q("已切换 · Codex 极光");}else if(t==="codex"){i="tear";Q("已切换 · 撕裂");}else if(t==="tear"){i="ai";Q("已切换 · AI 工作台");}else{i="ai";Q("已切换 · AI 工作台");}if(t==="ai"||!t){document.documentElement.setAttribute("data-theme","paper");}else if(t==="paper"){document.documentElement.setAttribute("data-theme","bamboo");}else if(t==="bamboo"){document.documentElement.setAttribute("data-theme","plum");}else if(t==="plum"){document.documentElement.setAttribute("data-theme","night");}else if(t==="night"){document.documentElement.setAttribute("data-theme","pink");}else if(t==="pink"){document.documentElement.setAttribute("data-theme","codex");}else if(t==="codex"){document.documentElement.setAttribute("data-theme","tear");}else{document.documentElement.setAttribute("data-theme","ai");}localStorage.setItem("tzs_theme",i);try{if(window.pywebview&&window.pywebview.api&&window.pywebview.api.save_theme){window.pywebview.api.save_theme(localStorage.getItem("tzs_theme"));}}catch(e){}}
function FONTADJ(d){var cur=parseInt(localStorage.getItem("tzs_fs")||"100",10);var step=d>0?10:-10;var v=cur+step;if(v<80)v=80;if(v>130)v=130;localStorage.setItem("tzs_fs",String(v));document.documentElement.style.setProperty("--font-scale",String(v));Q("字号 "+(v===100?"标准":(v>100?"+"+(v-100)+"%":"−"+(100-v)+"%")));}
function FONTR(){var v=parseInt(localStorage.getItem("tzs_fs")||"100",10);if(!v||isNaN(v))v=100;document.documentElement.style.setProperty("--font-scale",String(v));}
function U(){var dm=document.querySelector("#memberCount");if(dm)dm.textContent=D.members.filter(function(m){return m.memberType==="团员";}).length;var ds=document.querySelector("#studentCount");if(ds)ds.textContent=D.members.length;var dt=document.querySelector("#todoCount");if(dt)dt.textContent=D.todos.filter(function(t){return !t.done;}).length;}
var INK={mountain:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M6 50 L22 16 L30 34 L38 24 L58 50"/><path d="M6 50 H58" opacity=".45"/></svg>',bamboo:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M32 56 V12"/><path d="M32 42 C20 38 18 28 30 24" opacity=".8"/><path d="M32 32 C44 28 46 18 34 14" opacity=".8"/></svg>',plum:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M14 52 C14 30 30 16 52 10"/><path d="M24 44 C24 36 30 30 38 26"/><circle cx="22" cy="46" r="2.6" fill="currentColor" stroke="none"/><circle cx="30" cy="38" r="2.2" fill="currentColor" stroke="none"/><circle cx="40" cy="28" r="2" fill="currentColor" stroke="none"/></svg>',brush:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M10 54 L44 18 M44 18 C50 13 54 17 48 22"/><path d="M10 54 C15 49 20 53 15 58 Z" fill="currentColor" stroke="none"/></svg>',field:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M8 22 H56 M8 40 H56 M8 58 H56"/><path d="M20 10 C20 17 16 21 12 24 M44 10 C44 17 40 21 36 24" opacity=".7"/></svg>',coin:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3"><circle cx="32" cy="32" r="21"/><rect x="26" y="26" width="12" height="12" rx="2"/></svg>',seal:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect x="15" y="9" width="34" height="46" rx="4"/><path d="M24 24 H40 M24 34 H40 M24 44 H33"/></svg>',cloud:'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M18 42 C13 42 11 37 15 34 C13 29 20 26 25 30 C27 25 36 25 38 30 C43 28 47 33 43 38 C46 40 44 45 39 44 Z"/></svg>'};
function RC(){return'<div class=card>暂无数据</div>';}
function EMP(icon,text,btnHtml){
var svg=INK[icon]||INK.cloud;
return '<div class=empty>'+svg+'<div style="font-size:14px;color:var(--text3)">'+text+'</div>'+(btnHtml?'<div style=margin-top:14px>'+btnHtml+'</div>':'')+'</div>';}

/* ---- TZS 注册表(阶段A:全局名保留,仅登记) ---- */
window.TZS = window.TZS || {};
window.TZS.core_utils = {
  Q,
  Z,
  CONFIRM,
  CFM,
  V,
  N,
  R,
  C,
  FONTADJ,
  FONTR,
  U,
  RC,
  EMP,
};
